name: Matrix strategy

on: push

jobs:
  first-job:
    strategy:
      matrix:
        os: [ubuntu-latest, mac-os, windows-latest]
    runs-on: ${matrix.os}
    steps:
      - name: print OS name
        run : echo "$RUNNER_OS"
      
      - name: print python version
        run : python3 --version

      
