name: Multiple Jobs

on: push

jobs:
  Information:
    steps:
      - name: Information
        run : echo "information"

  Lint:
    steps:
      - name: Lint
        run : echo "lint"

  Build: 
    steps:
      - name: Build
        run : echo "build"